# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: git
      name: UrbanEnvi.DevOps

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - hotfix/*
      - support/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-dev
  - group: nuget-dev
  - group: helm-dev

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      # - job: NuGet
      #   displayName: Build NuGet package
      #   steps:
      #     - template: pipelines/nuget-pack-push.yaml@templates
      #       parameters:
      #         solution: "UrbanEnvi.Addresses.sln"
      - job: Docker
        displayName: Build Docker image
        steps:
          - template: pipelines/docker-build-push.yaml@templates
      - job: Helm
        displayName: Publish Helm chart
        steps:
          - template: pipelines/helm-publish.yaml@templates
