# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: templates
      type: git
      name: UrbanEnvi.DevOps

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
      - hotfix/*
      - support/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-dev
  - group: nuget-dev

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Docker
        displayName: Build Docker image
        steps:
          - template: pipelines/docker/publish.yaml@templates
