apiVersion: v2
name: projects
description: A Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: k8s
    version: 0.1.0
    repository: "file://./../DevOps/k8s"
