kind: Service
apiVersion: v1
metadata:
  name: projects
  labels:
    app.kubernetes.io/name: 'projects'
    app.kubernetes.io/part-of: 'UrbanEnvi'
spec:
  selector:
    app.kubernetes.io/name: projects
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80